version: '3.7'

services:
  # 서비스명
  my-backend-main-project:
    # Dockerfile
    build:
      # 위치
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      #  도커 밖(원본) : 도커 안(도커내부)
      - ./src:/myfolder/src

  my-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydocker02'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  my-redis:
    image: redis:latest
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:7.17.3
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
  
  logstash:
    image: logstash:7.17.3
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar
      - ./elk/logstash/template.json:/usr/share/logstash/template.json