version: "3.7"

services:
  # 서비스명
  my-backend:
    # Dockerfile
    build:
      # 위치
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      #  도커 밖(원본) : 도커 안(도커내부)
      - ./index.js:/myfolder/index.js
      - ./phone.js:/myfolder/phone.js
      - ./signup.js:/myfolder/signup.js
      - ./utils.js:/myfolder/utils.js
      - ./users.js:/myfolder/users.js
      - ./coffee.js:/myfolder/coffee.js
      - ./swagger/config.js:/myfolder/swagger/config.js
      - ./swagger/starbucks.swagger.js:/myfolder/swagger/starbucks.swagger.js
      - ./swagger/tokens.swagger.js:/myfolder/swagger/tokens.swagger.js
      - ./swagger/users.swagger.js:/myfolder/swagger/users.swagger.js

  my-database:
    image: mongo:latest
    ports:
      - 27017:27017
