steps:
  # 1단계 docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args: 
      - -f
      - docker-compose.prod.yaml
      - build
  # 2단계  docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - push
  # 3단계 kubectl set image deployment/class-0503-nest class-0503-sha256-1=asia.....
  - name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - set
      - image
      - deployment/class-0503-nest
      - class-0503-sha256-1=asia.gcr.io/united-idea-347705/class_0503:4      
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=class-0503-01
  
  